exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

site_name: Vax.Codes
root_url: https://vax.codes
support_email: support@vax.codes
join_group_email: join@vax.codes
create_group_email: create-group@vax.codes
register_issuer_email: register@vax.codes

collections:
  groups:
    output: true
    permalink: /api/v1/groups/:title.json
  issuers:
    output: true
    permalink: /api/v1/issuers/:title.json

defaults:
  - scope:
      path: ""
      type: "groups"
    values:
      layout: "group_object"
  - scope:
      path: ""
      type: "issuers"
    values:
      layout: "issuer_object"
