exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

collections:
  groups:
    output: true
    permalink: /api/v1/groups/:title.json
  issuers:
    output: true
    permalink: /api/v1/issuers/:title.json

defaults:
  - scope:
      path: ""
      type: "groups"
    values:
      layout: "group_object"
  - scope:
      path: ""
      type: "issuers"
    values:
      layout: "issuer_object"
